# -*- encoding: utf-8; indent-tabs-mode: nil -*-

=encoding utf8

=head1 Présentation

Ce dépôt contient plusieurs utilitaires
pour les divers programmes de calendrier
républicain auxquels je m'intéresse.
Sauf exception, chaque programme est diffusé
avec les mêmes termes de licence que Perl :
la licence GPL version 1 ou ultérieure,
ou la licence artistique.

=head1 Installation

Une prérequis commun à tous les programmes est
l'installation de Perl 5.10 ou plus récent, ainsi
que des modules F<DateTime> et
F<DateTime::Calendar::FrenchRevolutionary>.
Si un programme particulier a besoin d'autre
chose, cela sera marqué dans sa documentation.
Utilisez C<perlpod> I<nom-du-programme> 
et lisez le paragraphe I<DEPENDANCES>.

=head1 gen-tests

Ce programme génère des fichiers de tests pour
divers programme de calendrier républicain.
Dans certains cas, le programme généré est
directement utilisable, dans d'autres cas
il faut quelques opérations d'édition pour
copier les lignes générées dans un fichier
source extérieur.

=head1 gen-feasts

Ce programme génère la liste des fêtes du
calendrier républicain, pour l'inclure dans le
programme cal-french.el d'Emacs ou d'autres
programmes.
